/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TravelManagement;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author ChibuezePaul
 */
public class Travel extends javax.swing.JFrame implements ActionListener {
    //Creates new form Travel   

    public Travel() {
        initComponents();
        this.setIconImage(new ImageIcon("C:\\Users\\Paul\\Documents\\NetBeansProjects\\Travel Management System\\src\\icons8_Bus_90px.png").getImage());
        setLocationRelativeTo(JOptionPane.getRootFrame());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReceipt = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        rbtnFClass = new javax.swing.JRadioButton();
        rbtnChild = new javax.swing.JRadioButton();
        rbtnEClass = new javax.swing.JRadioButton();
        rbtnSingle = new javax.swing.JRadioButton();
        rbtnReturn = new javax.swing.JRadioButton();
        rbtnBClass = new javax.swing.JRadioButton();
        rbtnAdult = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSname = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtStotal = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtTax = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        btnTicket = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        comDestination = new javax.swing.JComboBox<>();
        comDeparture = new javax.swing.JComboBox<>();
        rbtnVat = new javax.swing.JRadioButton();
        rbtnExtra = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        btnTicket1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("I_Travels Nigeria Limited");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(21, 27, 84));

        jLabel2.setBackground(new java.awt.Color(102, 102, 255));
        jLabel2.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("I_Travels Nigeria Limited >> Book Ticket");

        jLabel3.setFont(new java.awt.Font("DialogInput", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nigeria's First Local Flight...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(21, 27, 84));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Receipt", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Exotc350 Lt BT", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        txtReceipt.setEditable(false);
        txtReceipt.setColumns(2);
        txtReceipt.setRows(5);
        txtReceipt.setBorder(null);
        txtReceipt.setDragEnabled(true);
        jScrollPane1.setViewportView(txtReceipt);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(21, 27, 84));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        rbtnFClass.setBackground(new java.awt.Color(21, 27, 84));
        buttonGroup1.add(rbtnFClass);
        rbtnFClass.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        rbtnFClass.setForeground(new java.awt.Color(255, 255, 255));
        rbtnFClass.setText("First Bus");
        rbtnFClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFClassActionPerformed(evt);
            }
        });

        rbtnChild.setBackground(new java.awt.Color(21, 27, 84));
        buttonGroup3.add(rbtnChild);
        rbtnChild.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        rbtnChild.setForeground(new java.awt.Color(255, 255, 255));
        rbtnChild.setLabel("Child");
        rbtnChild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnChildActionPerformed(evt);
            }
        });

        rbtnEClass.setBackground(new java.awt.Color(21, 27, 84));
        buttonGroup1.add(rbtnEClass);
        rbtnEClass.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        rbtnEClass.setForeground(new java.awt.Color(255, 255, 255));
        rbtnEClass.setText("Third Bus");
        rbtnEClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEClassActionPerformed(evt);
            }
        });

        rbtnSingle.setBackground(new java.awt.Color(21, 27, 84));
        buttonGroup2.add(rbtnSingle);
        rbtnSingle.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        rbtnSingle.setForeground(new java.awt.Color(255, 255, 255));
        rbtnSingle.setText("Day");
        rbtnSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSingleActionPerformed(evt);
            }
        });

        rbtnReturn.setBackground(new java.awt.Color(21, 27, 84));
        buttonGroup2.add(rbtnReturn);
        rbtnReturn.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        rbtnReturn.setForeground(new java.awt.Color(255, 255, 255));
        rbtnReturn.setText("Night");
        rbtnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnReturnActionPerformed(evt);
            }
        });

        rbtnBClass.setBackground(new java.awt.Color(21, 27, 84));
        buttonGroup1.add(rbtnBClass);
        rbtnBClass.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        rbtnBClass.setForeground(new java.awt.Color(255, 255, 255));
        rbtnBClass.setText("Second Bus");
        rbtnBClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnBClassActionPerformed(evt);
            }
        });

        rbtnAdult.setBackground(new java.awt.Color(21, 27, 84));
        buttonGroup3.add(rbtnAdult);
        rbtnAdult.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        rbtnAdult.setForeground(new java.awt.Color(255, 255, 255));
        rbtnAdult.setText("Adult");
        rbtnAdult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAdultActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bus");
        jLabel7.setFocusTraversalPolicyProvider(true);

        jLabel8.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Age");
        jLabel8.setFocusTraversalPolicyProvider(true);

        jLabel9.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ticket");
        jLabel9.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rbtnEClass)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnBClass)
                            .addComponent(rbtnFClass)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnSingle)
                                    .addComponent(rbtnReturn))
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(67, 67, 67)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnChild)
                            .addComponent(rbtnAdult)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnFClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnBClass))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnAdult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnChild))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnSingle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnReturn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnEClass)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(21, 27, 84));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Surname");
        jLabel10.setFocusTraversalPolicyProvider(true);

        jLabel11.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Firstname");
        jLabel11.setFocusTraversalPolicyProvider(true);

        jLabel12.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Telephone");
        jLabel12.setFocusTraversalPolicyProvider(true);

        jLabel13.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("E.Mail");
        jLabel13.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFname)
                            .addComponent(txtSname)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTel)
                            .addComponent(txtEmail))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(21, 27, 84));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fare Cost");
        jLabel6.setFocusTraversalPolicyProvider(true);

        jLabel14.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tax");
        jLabel14.setFocusTraversalPolicyProvider(true);

        jLabel15.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Total");
        jLabel15.setFocusTraversalPolicyProvider(true);

        txtStotal.setEditable(false);

        txtTotal.setEditable(false);

        txtTax.setEditable(false);

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReset.setForeground(new java.awt.Color(21, 27, 84));
        btnReset.setText("Reset");
        btnReset.setBorderPainted(false);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTotal.setForeground(new java.awt.Color(21, 27, 84));
        btnTotal.setText("Total");
        btnTotal.setBorderPainted(false);
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotal)
                    .addComponent(txtTax)
                    .addComponent(txtStotal)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtStotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnTotal))
                .addGap(6, 6, 6))
        );

        btnPay.setBackground(new java.awt.Color(21, 27, 84));
        btnPay.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("Pay Now");
        btnPay.setBorderPainted(false);
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        btnTicket.setBackground(new java.awt.Color(21, 27, 84));
        btnTicket.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTicket.setForeground(new java.awt.Color(255, 255, 255));
        btnTicket.setText("Ticket");
        btnTicket.setBorderPainted(false);
        btnTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTicketMousePressed(evt);
            }
        });
        btnTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(21, 27, 84));
        jLabel17.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(21, 27, 84));
        jLabel17.setText("Departure");
        jLabel17.setFocusTraversalPolicyProvider(true);

        comDestination.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        comDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "ABUJA", "AKWA IBOM", "IMO", "KANO", "LAGOS" }));

        comDeparture.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        comDeparture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "ABUJA", "AKWA IBOM", "IMO", "KANO", "LAGOS" }));

        rbtnVat.setBackground(new java.awt.Color(21, 27, 84));
        rbtnVat.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        rbtnVat.setForeground(new java.awt.Color(255, 255, 255));
        rbtnVat.setText(" 5% VAT");

        rbtnExtra.setBackground(new java.awt.Color(21, 27, 84));
        rbtnExtra.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        rbtnExtra.setForeground(new java.awt.Color(255, 255, 255));
        rbtnExtra.setText("Extra Luggage");

        jLabel18.setBackground(new java.awt.Color(21, 27, 84));
        jLabel18.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(21, 27, 84));
        jLabel18.setText("Destination");
        jLabel18.setFocusTraversalPolicyProvider(true);

        btnTicket1.setBackground(new java.awt.Color(21, 27, 84));
        btnTicket1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTicket1.setForeground(new java.awt.Color(255, 255, 255));
        btnTicket1.setText("Print");
        btnTicket1.setBorderPainted(false);
        btnTicket1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTicket1MousePressed(evt);
            }
        });
        btnTicket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicket1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(rbtnVat)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnExtra))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTicket1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comDeparture, comDestination});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comDestination))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtnVat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtnExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTicket1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comDeparture, comDestination});

        jPanel7.setBackground(new java.awt.Color(21, 27, 84));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel16.setFont(new java.awt.Font("Exotc350 Lt BT", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ISoft");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleName("Ticket Booking");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //********Global Variables Declaration********//
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String query;
    String db = "jdbc:mysql://localhost:3307/travel";
    String user = "paul";
    String pass = "";
    int num;
    String ref;

    //*********************************************//
    public String setRef() {
        do {
            for (num = 0; num <= 10; num++) {
                int i = (1234 + (int) (Math.random() * 1000));
                ref = "ITR";
                ref += i + 4321;
            }
        } while (btnTicket.isSelected());
        return ref;
    }

    public double firstSingle(double location, double vat, double luggage) {
        TravelCost[0] = location + fClass + Single + vat + luggage;
        String subTotal = String.format("N%.2f", TravelCost[0]);
        txtStotal.setText(subTotal);
        TravelCost[1] = (TravelCost[0] * (iTax / 100));
        String Tax = String.format("N%.2f", TravelCost[1]);
        txtTax.setText(Tax);
        String Total = String.format("N%.2f", TravelCost[0] + TravelCost[1]);
        txtTotal.setText(Total);
        return 0;
    }

    public double firstReturn(double location, double vat, double luggage) {
        TravelCost[0] = location + fClass + Return + vat + luggage;
        String subTotal = String.format("N%.2f", TravelCost[0]);
        txtStotal.setText(subTotal);
        TravelCost[1] = (TravelCost[0] * (iTax / 100));
        String Tax = String.format("N%.2f", TravelCost[1]);
        txtTax.setText(Tax);
        String Total = String.format("N%.2f", TravelCost[0] + TravelCost[1]);
        txtTotal.setText(Total);
        return 0;
    }

    public double businessSingle(double location, double vat, double luggage) {
        TravelCost[0] = location + bClass + Single + vat + luggage;
        String subTotal = String.format("N%.2f", TravelCost[0]);
        txtStotal.setText(subTotal);
        TravelCost[1] = (TravelCost[0] * (iTax / 100));
        String Tax = String.format("N%.2f", TravelCost[1]);
        txtTax.setText(Tax);
        String Total = String.format("N%.2f", TravelCost[0] + TravelCost[1]);
        txtTotal.setText(Total);
        return 0;
    }

    public double businessReturn(double location, double vat, double luggage) {
        TravelCost[0] = location + bClass + Return + vat + luggage;
        String subTotal = String.format("N%.2f", TravelCost[0]);
        txtStotal.setText(subTotal);
        TravelCost[1] = (TravelCost[0] * (iTax / 100));
        String Tax = String.format("N%.2f", TravelCost[1]);
        txtTax.setText(Tax);
        String Total = String.format("N%.2f", TravelCost[0] + TravelCost[1]);
        txtTotal.setText(Total);
        return 0;
    }

    public double economySingle(double location, double vat, double luggage) {
        TravelCost[0] = location + eClass + Single + vat + luggage;
        String subTotal = String.format("N%.2f", TravelCost[0]);
        txtStotal.setText(subTotal);
        TravelCost[1] = (TravelCost[0] * (iTax / 100));
        String Tax = String.format("N%.2f", TravelCost[1]);
        txtTax.setText(Tax);
        String Total = String.format("N%.2f", TravelCost[0] + TravelCost[1]);
        txtTotal.setText(Total);
        return 0;
    }

    public double economyReturn(double location, double vat, double luggage) {
        TravelCost[0] = location + eClass + Return + vat + luggage;
        String subTotal = String.format("N%.2f", TravelCost[0]);
        txtStotal.setText(subTotal);
        TravelCost[1] = (TravelCost[0] * (iTax / 100));
        String Tax = String.format("N%.2f", TravelCost[1]);
        txtTax.setText(Tax);
        String Total = String.format("N%.2f", TravelCost[0] + TravelCost[1]);
        txtTotal.setText(Total);
        return 0;
    }

    //variables declaration
    JFrame frame = new JFrame();

    double ABUJA = 400;
    double AKWA_IBOM = 600;
    double IMO = 500;
    double KANO = 700;
    double LAGOS = 300;

    double fClass = 350;
    double bClass = 250;
    double eClass = 150;

    double Single = 50;
    double Return = 100;

    double VAT = 5;
    double eLuggage = 5;

    double iTax = 5;
    double[] TravelCost = new double[20];

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(null, "Confirm if you want to exit", "Ticket Booking",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            this.dispose();
            Homepage.main(null);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed

    }//GEN-LAST:event_btnTicketActionPerformed

    private void btnTicketMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTicketMousePressed

        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat myDateFormat = new SimpleDateFormat("dd-MMMMMMMM-yy");
        String myDate = (myDateFormat.format(timer.getTime()));

        SimpleDateFormat myTimeFormat = new SimpleDateFormat("hh:mm");
        String myTime = (myTimeFormat.format(timer.getTime()));

        try {
            txtReceipt.setText("Ticket Booking System\n\n" + "Ref: " + setRef() + "\t" + myTime + "   " + myDate + "\n------------------------------------------------"
                    + "\nSurname:\t" + txtSname.getText() + "\nFirstname:\t" + txtFname.getText() + "\nTelephone:\t" + txtTel.getText()
                    + "\nBus Type:\t" + buttonGroup1.getSelection().getActionCommand() + "\nTicket Time:\t" + buttonGroup2.getSelection().getActionCommand()
                    + "\nAge:\t" + buttonGroup3.getSelection().getActionCommand() + "\nDeparture:\t" + comDeparture.getSelectedItem()
                    + "\nDestination:\t" + comDestination.getSelectedItem() + "\nTicket Date:\t" + myDate + "\n------------------------------------------------" + "\nSub-Total:\t" + txtStotal.getText()
                    + "\nTax:\t" + txtTax.getText() + "\nTotal:\t" + txtTotal.getText());;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Incomplete Passenger Details", "Ticket Booking", 3);
        }
    }//GEN-LAST:event_btnTicketMousePressed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        new Payment().setVisible(true);
        Payment.txtPayable.setText(txtTotal.getText());
    }//GEN-LAST:event_btnPayActionPerformed

    //String obj = String.valueOf(txtTotal.getText());
    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        //Location : ABUJA(start)========================================================================================
        //FirstClass/Single Ticket
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnFClass.isSelected()) && (rbtnSingle.isSelected())) {
            firstSingle(ABUJA, 0, 0);
        }

        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnFClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnVat.isSelected())) {
            firstSingle(ABUJA, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnFClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnExtra.isSelected())) {
            firstSingle(ABUJA, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnFClass.isSelected())
                && (rbtnSingle.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            firstSingle(ABUJA, VAT, eLuggage);
        }
        //FirstClass/Return Ticket
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnFClass.isSelected()) && (rbtnReturn.isSelected())) {
            firstReturn(ABUJA, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnFClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnVat.isSelected())) {
            firstReturn(ABUJA, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnFClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnExtra.isSelected())) {
            firstReturn(ABUJA, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnFClass.isSelected())
                && (rbtnReturn.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            firstReturn(ABUJA, VAT, eLuggage);
        }

        //BusinessClass/Single Ticket
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnBClass.isSelected()) && (rbtnSingle.isSelected())) {
            businessSingle(ABUJA, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnBClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnVat.isSelected())) {
            businessSingle(ABUJA, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnBClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnExtra.isSelected())) {
            businessSingle(ABUJA, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnBClass.isSelected())
                && (rbtnSingle.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            businessSingle(ABUJA, VAT, eLuggage);
        }
        //BusinessClass/Return Ticket
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnBClass.isSelected()) && (rbtnReturn.isSelected())) {
            businessReturn(ABUJA, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnBClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnVat.isSelected())) {
            businessReturn(ABUJA, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnBClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnExtra.isSelected())) {
            businessReturn(ABUJA, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnBClass.isSelected())
                && (rbtnReturn.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            businessReturn(ABUJA, VAT, eLuggage);
        }
        //EconomyClass/Single Ticket
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnEClass.isSelected()) && (rbtnSingle.isSelected())) {
            economySingle(ABUJA, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnEClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnVat.isSelected())) {
            economySingle(ABUJA, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnEClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnExtra.isSelected())) {
            economySingle(ABUJA, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnEClass.isSelected())
                && (rbtnSingle.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            economySingle(ABUJA, VAT, eLuggage);
        }
        //EconomyClass/Return Ticket
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnEClass.isSelected()) && (rbtnReturn.isSelected())) {
            economyReturn(ABUJA, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnEClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnVat.isSelected())) {
            economyReturn(ABUJA, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnEClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnExtra.isSelected())) {
            economyReturn(ABUJA, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("ABUJA")) && (rbtnEClass.isSelected())
                && (rbtnReturn.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            economyReturn(ABUJA, VAT, eLuggage);
        }
        //Location : ABUJA(stop)========================================================================================

        //Location : IMO(start)=========================================================================================
        //FirstClass/Single Ticket
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnFClass.isSelected()) && (rbtnSingle.isSelected())) {
            firstSingle(IMO, 0, 0);
        }

        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnFClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnVat.isSelected())) {
            firstSingle(IMO, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnFClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnExtra.isSelected())) {
            firstSingle(IMO, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnFClass.isSelected())
                && (rbtnSingle.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            firstSingle(IMO, VAT, eLuggage);
        }
        //FirstClass/Return Ticket
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnFClass.isSelected()) && (rbtnReturn.isSelected())) {
            firstReturn(IMO, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnFClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnVat.isSelected())) {
            firstReturn(IMO, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnFClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnExtra.isSelected())) {
            firstReturn(IMO, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnFClass.isSelected())
                && (rbtnReturn.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            firstReturn(IMO, VAT, eLuggage);
        }

        //BusinessClass/Single Ticket
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnBClass.isSelected()) && (rbtnSingle.isSelected())) {
            businessSingle(IMO, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnBClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnVat.isSelected())) {
            businessSingle(IMO, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnBClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnExtra.isSelected())) {
            businessSingle(IMO, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnBClass.isSelected())
                && (rbtnSingle.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            businessSingle(IMO, VAT, eLuggage);
        }
        //BusinessClass/Return Ticket
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnBClass.isSelected()) && (rbtnReturn.isSelected())) {
            businessReturn(IMO, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnBClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnVat.isSelected())) {
            businessReturn(IMO, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnBClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnExtra.isSelected())) {
            businessReturn(IMO, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnBClass.isSelected())
                && (rbtnReturn.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            businessReturn(IMO, VAT, eLuggage);
        }
        //EconomyClass/Single Ticket
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnEClass.isSelected()) && (rbtnSingle.isSelected())) {
            economySingle(IMO, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnEClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnVat.isSelected())) {
            economySingle(IMO, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnEClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnExtra.isSelected())) {
            economySingle(IMO, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnEClass.isSelected())
                && (rbtnSingle.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            economySingle(IMO, VAT, eLuggage);
        }
        //EconomyClass/Return Ticket
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnEClass.isSelected()) && (rbtnReturn.isSelected())) {
            economyReturn(IMO, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnEClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnVat.isSelected())) {
            economyReturn(IMO, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnEClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnExtra.isSelected())) {
            economyReturn(IMO, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("IMO")) && (rbtnEClass.isSelected())
                && (rbtnReturn.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            economyReturn(IMO, VAT, eLuggage);
        }
        //Location : IMO(stop)==========================================================================================

        //Location : LAGOS(start)==========================================================================================
        //FirstClass/Single Ticket
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnFClass.isSelected()) && (rbtnSingle.isSelected())) {
            firstSingle(LAGOS, 0, 0);
        }

        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnFClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnVat.isSelected())) {
            firstSingle(LAGOS, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnFClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnExtra.isSelected())) {
            firstSingle(LAGOS, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnFClass.isSelected())
                && (rbtnSingle.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            firstSingle(LAGOS, VAT, eLuggage);
        }
        //FirstClass/Return Ticket
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnFClass.isSelected()) && (rbtnReturn.isSelected())) {
            firstReturn(LAGOS, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnFClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnVat.isSelected())) {
            firstReturn(LAGOS, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnFClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnExtra.isSelected())) {
            firstReturn(LAGOS, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnFClass.isSelected())
                && (rbtnReturn.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            firstReturn(LAGOS, VAT, eLuggage);
        }

        //BusinessClass/Single Ticket
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnBClass.isSelected()) && (rbtnSingle.isSelected())) {
            businessSingle(LAGOS, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnBClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnVat.isSelected())) {
            businessSingle(LAGOS, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnBClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnExtra.isSelected())) {
            businessSingle(LAGOS, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnBClass.isSelected())
                && (rbtnSingle.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            businessSingle(LAGOS, VAT, eLuggage);
        }
        //BusinessClass/Return Ticket
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnBClass.isSelected()) && (rbtnReturn.isSelected())) {
            businessReturn(LAGOS, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnBClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnVat.isSelected())) {
            businessReturn(LAGOS, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnBClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnExtra.isSelected())) {
            businessReturn(LAGOS, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnBClass.isSelected())
                && (rbtnReturn.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            businessReturn(LAGOS, VAT, eLuggage);
        }
        //EconomyClass/Single Ticket
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnEClass.isSelected()) && (rbtnSingle.isSelected())) {
            economySingle(LAGOS, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnEClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnVat.isSelected())) {
            economySingle(LAGOS, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnEClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnExtra.isSelected())) {
            economySingle(LAGOS, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnEClass.isSelected())
                && (rbtnSingle.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            economySingle(LAGOS, VAT, eLuggage);
        }
        //EconomyClass/Return Ticket
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnEClass.isSelected()) && (rbtnReturn.isSelected())) {
            economyReturn(LAGOS, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnEClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnVat.isSelected())) {
            economyReturn(LAGOS, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnEClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnExtra.isSelected())) {
            economyReturn(LAGOS, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("LAGOS")) && (rbtnEClass.isSelected())
                && (rbtnReturn.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            economyReturn(LAGOS, VAT, eLuggage);
        }
        //Location : LAGOS(stop)==========================================================================================

        //Location : KANO(start)==========================================================================================
        //FirstClass/Single Ticket
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnFClass.isSelected()) && (rbtnSingle.isSelected())) {
            firstSingle(KANO, 0, 0);
        }

        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnFClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnVat.isSelected())) {
            firstSingle(KANO, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnFClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnExtra.isSelected())) {
            firstSingle(KANO, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnFClass.isSelected())
                && (rbtnSingle.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            firstSingle(KANO, VAT, eLuggage);
        }
        //FirstClass/Return Ticket
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnFClass.isSelected()) && (rbtnReturn.isSelected())) {
            firstReturn(KANO, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnFClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnVat.isSelected())) {
            firstReturn(KANO, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnFClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnExtra.isSelected())) {
            firstReturn(KANO, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnFClass.isSelected())
                && (rbtnReturn.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            firstReturn(KANO, VAT, eLuggage);
        }

        //BusinessClass/Single Ticket
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnBClass.isSelected()) && (rbtnSingle.isSelected())) {
            businessSingle(KANO, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnBClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnVat.isSelected())) {
            businessSingle(KANO, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnBClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnExtra.isSelected())) {
            businessSingle(KANO, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnBClass.isSelected())
                && (rbtnSingle.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            businessSingle(KANO, VAT, eLuggage);
        }
        //BusinessClass/Return Ticket
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnBClass.isSelected()) && (rbtnReturn.isSelected())) {
            businessReturn(KANO, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnBClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnVat.isSelected())) {
            businessReturn(KANO, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnBClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnExtra.isSelected())) {
            businessReturn(KANO, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnBClass.isSelected())
                && (rbtnReturn.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            businessReturn(KANO, VAT, eLuggage);
        }
        //EconomyClass/Single Ticket
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnEClass.isSelected()) && (rbtnSingle.isSelected())) {
            economySingle(KANO, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnEClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnVat.isSelected())) {
            economySingle(KANO, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnEClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnExtra.isSelected())) {
            economySingle(KANO, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnEClass.isSelected())
                && (rbtnSingle.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            economySingle(KANO, VAT, eLuggage);
        }
        //EconomyClass/Return Ticket
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnEClass.isSelected()) && (rbtnReturn.isSelected())) {
            economyReturn(KANO, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnEClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnVat.isSelected())) {
            economyReturn(KANO, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnEClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnExtra.isSelected())) {
            economyReturn(KANO, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("KANO")) && (rbtnEClass.isSelected())
                && (rbtnReturn.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            economyReturn(KANO, VAT, eLuggage);
        }
        //Location : KANO(stop)=============================================================================================

        //Location : AKWA_IBOM(start)=======================================================================================
        //FirstClass/Single Ticket
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnFClass.isSelected()) && (rbtnSingle.isSelected())) {
            firstSingle(AKWA_IBOM, 0, 0);
        }

        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnFClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnVat.isSelected())) {
            firstSingle(AKWA_IBOM, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnFClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnExtra.isSelected())) {
            firstSingle(AKWA_IBOM, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnFClass.isSelected())
                && (rbtnSingle.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            firstSingle(AKWA_IBOM, VAT, eLuggage);
        }
        //FirstClass/Return Ticket
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnFClass.isSelected()) && (rbtnReturn.isSelected())) {
            firstReturn(AKWA_IBOM, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnFClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnVat.isSelected())) {
            firstReturn(AKWA_IBOM, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnFClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnExtra.isSelected())) {
            firstReturn(AKWA_IBOM, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnFClass.isSelected())
                && (rbtnReturn.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            firstReturn(AKWA_IBOM, VAT, eLuggage);
        }

        //BusinessClass/Single Ticket
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnBClass.isSelected()) && (rbtnSingle.isSelected())) {
            businessSingle(AKWA_IBOM, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnBClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnVat.isSelected())) {
            businessSingle(AKWA_IBOM, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnBClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnExtra.isSelected())) {
            businessSingle(AKWA_IBOM, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnBClass.isSelected())
                && (rbtnSingle.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            businessSingle(AKWA_IBOM, VAT, eLuggage);
        }
        //BusinessClass/Return Ticket
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnBClass.isSelected()) && (rbtnReturn.isSelected())) {
            businessReturn(AKWA_IBOM, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnBClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnVat.isSelected())) {
            businessReturn(AKWA_IBOM, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnBClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnExtra.isSelected())) {
            businessReturn(AKWA_IBOM, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnBClass.isSelected())
                && (rbtnReturn.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            businessReturn(AKWA_IBOM, VAT, eLuggage);
        }
        //EconomyClass/Single Ticket
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnEClass.isSelected()) && (rbtnSingle.isSelected())) {
            economySingle(AKWA_IBOM, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnEClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnVat.isSelected())) {
            economySingle(AKWA_IBOM, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnEClass.isSelected()) && (rbtnSingle.isSelected())
                && (rbtnExtra.isSelected())) {
            economySingle(AKWA_IBOM, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnEClass.isSelected())
                && (rbtnSingle.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            economySingle(AKWA_IBOM, VAT, eLuggage);
        }
        //EconomyClass/Return Ticket
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnEClass.isSelected()) && (rbtnReturn.isSelected())) {
            economyReturn(AKWA_IBOM, 0, 0);
        }
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnEClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnVat.isSelected())) {
            economyReturn(AKWA_IBOM, VAT, 0);
        }
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnEClass.isSelected()) && (rbtnReturn.isSelected())
                && (rbtnExtra.isSelected())) {
            economyReturn(AKWA_IBOM, eLuggage, 0);
        }
        if ((comDestination.getSelectedItem().equals("AKWA IBOM")) && (rbtnEClass.isSelected())
                && (rbtnReturn.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            economyReturn(AKWA_IBOM, VAT, eLuggage);
        } //Location : AKWA_IBOM(stop)=======================================================================================
        //No departure selected
        else if (comDeparture.getSelectedItem().equals("NONE")
                && (comDestination.getSelectedItem().equals("ABUJA") || comDestination.getSelectedItem().equals("IMO")
                || comDestination.getSelectedItem().equals("LAGOS") || comDestination.getSelectedItem().equals("KANO")
                || comDestination.getSelectedItem().equals("AKWA IBOM"))
                && (rbtnFClass.isSelected() || rbtnBClass.isSelected() || rbtnEClass.isSelected())
                && (rbtnSingle.isSelected() || rbtnReturn.isSelected())) {
            JOptionPane.showMessageDialog(frame, "Select a departure point", "Departure", ERROR_MESSAGE);
        } else if (comDeparture.getSelectedItem().equals("NONE")
                && (comDestination.getSelectedItem().equals("ABUJA") || comDestination.getSelectedItem().equals("IMO")
                || comDestination.getSelectedItem().equals("LAGOS") || comDestination.getSelectedItem().equals("KANO")
                || comDestination.getSelectedItem().equals("AKWA IBOM"))
                && (rbtnFClass.isSelected() || rbtnBClass.isSelected() || rbtnEClass.isSelected())
                && (rbtnSingle.isSelected() || rbtnReturn.isSelected()) && (rbtnVat.isSelected())) {
            JOptionPane.showMessageDialog(frame, "Select a departure point", "Departure", ERROR_MESSAGE);
        } else if (comDeparture.getSelectedItem().equals("NONE")
                && (comDestination.getSelectedItem().equals("ABUJA") || comDestination.getSelectedItem().equals("IMO")
                || comDestination.getSelectedItem().equals("LAGOS") || comDestination.getSelectedItem().equals("KANO")
                || comDestination.getSelectedItem().equals("AKWA IBOM"))
                && (rbtnFClass.isSelected() || rbtnBClass.isSelected() || rbtnEClass.isSelected())
                && (rbtnSingle.isSelected() || rbtnReturn.isSelected()) && (rbtnExtra.isSelected())) {
            JOptionPane.showMessageDialog(frame, "Select a departure point", "Departure", ERROR_MESSAGE);
        } else if (comDeparture.getSelectedItem().equals("NONE")
                && (comDestination.getSelectedItem().equals("ABUJA") || comDestination.getSelectedItem().equals("IMO")
                || comDestination.getSelectedItem().equals("LAGOS") || comDestination.getSelectedItem().equals("KANO")
                || comDestination.getSelectedItem().equals("AKWA IBOM"))
                && (rbtnFClass.isSelected() || rbtnBClass.isSelected() || rbtnEClass.isSelected())
                && (rbtnSingle.isSelected() || rbtnReturn.isSelected()) && (rbtnVat.isSelected()) && (rbtnExtra.isSelected())) {
            JOptionPane.showMessageDialog(frame, "Select a departure point", "Departure", ERROR_MESSAGE);
        }

        try {
            con = DriverManager.getConnection(db, user, pass);

            query = "INSERT INTO travel.ticketbooking (`TICKET_NUMBER`,`SURNAME`,"
                    + "`NAME`,"
                    + "`TELEPHONE`,"
                    + "`DEPARTURE`,"
                    + "`DESTINATION`,"
                    + "`FLIGHT`,"
                    + "`TICKET`,"
                    + "`AMOUNT`,"
                    + "`FLIGHT_DATE`) VALUES(?,?,?,?,?,?,?,?,?,?)";

            pst = con.prepareStatement(query);

            Calendar timer = Calendar.getInstance();
            timer.getTime();
            SimpleDateFormat myDateFormat = new SimpleDateFormat("dd-MMMMMMMM-Y");
            String myDate = (myDateFormat.format(timer.getTime()));

            pst.setString(1, setRef());
            pst.setString(2, txtSname.getText());
            pst.setString(3, txtFname.getText());
            pst.setString(4, txtTel.getText());
            pst.setString(5, (String) comDeparture.getSelectedItem());
            pst.setString(6, (String) comDestination.getSelectedItem());
            pst.setString(7, buttonGroup1.getSelection().getActionCommand());
            pst.setString(8, buttonGroup2.getSelection().getActionCommand());
            pst.setString(9, txtTotal.getText());
            pst.setString(10, myDate);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Ticket Booked Successfully", "Ticket Booking", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Please Contact the admin", "Ticket Booking", 3);
        }
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtSname.setText(null);
        txtFname.setText(null);
        txtTel.setText(null);
        txtEmail.setText(null);
        txtStotal.setText(null);
        txtTax.setText(null);
        txtTotal.setText(null);
        txtReceipt.setText(null);
        rbtnVat.setSelected(false);
        rbtnExtra.setSelected(false);
        comDeparture.setSelectedItem("NONE");
        comDestination.setSelectedItem("NONE");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
    }//GEN-LAST:event_btnResetActionPerformed

    private void rbtnAdultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAdultActionPerformed
        if (rbtnAdult.isSelected()) {
            rbtnAdult.setActionCommand("Adult");
        } else {
            rbtnAdult.setActionCommand("----");
        }
    }//GEN-LAST:event_rbtnAdultActionPerformed

    private void rbtnBClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnBClassActionPerformed
        if (rbtnBClass.isSelected()) {
            rbtnBClass.setActionCommand("Third Bus");
        } else {
            rbtnBClass.setActionCommand("----");
        }
    }//GEN-LAST:event_rbtnBClassActionPerformed

    private void rbtnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnReturnActionPerformed
        if (rbtnReturn.isSelected()) {
            rbtnReturn.setActionCommand("Night");
        } else {
            rbtnReturn.setActionCommand("----");
        }
    }//GEN-LAST:event_rbtnReturnActionPerformed

    private void rbtnSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSingleActionPerformed
        if (rbtnSingle.isSelected()) {
            rbtnSingle.setActionCommand("Day");
        } else {
            rbtnSingle.setActionCommand("----");
        }
    }//GEN-LAST:event_rbtnSingleActionPerformed

    private void rbtnEClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEClassActionPerformed
        if (rbtnEClass.isSelected()) {
            rbtnEClass.setActionCommand("Second Bus");
        } else {
            rbtnEClass.setActionCommand("----");
        }
    }//GEN-LAST:event_rbtnEClassActionPerformed

    private void rbtnChildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnChildActionPerformed
        if (rbtnChild.isSelected()) {
            rbtnChild.setActionCommand("Child");
        } else {
            rbtnChild.setActionCommand("----");
        }
    }//GEN-LAST:event_rbtnChildActionPerformed

    private void rbtnFClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFClassActionPerformed
        if (rbtnFClass.isSelected()) {
            rbtnFClass.setActionCommand("First Bus");
        } else {
            rbtnFClass.setActionCommand("----");
        }
    }//GEN-LAST:event_rbtnFClassActionPerformed

    private void btnTicket1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTicket1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTicket1MousePressed

    private void btnTicket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicket1ActionPerformed
        try {
            txtReceipt.print();
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null, "Please Contact the admin");
        }
    }//GEN-LAST:event_btnTicket1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Travel".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Travel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Travel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Travel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Travel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Travel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnPay;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTicket;
    private javax.swing.JButton btnTicket1;
    private javax.swing.JButton btnTotal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> comDeparture;
    private javax.swing.JComboBox<String> comDestination;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnAdult;
    private javax.swing.JRadioButton rbtnBClass;
    private javax.swing.JRadioButton rbtnChild;
    private javax.swing.JRadioButton rbtnEClass;
    private javax.swing.JRadioButton rbtnExtra;
    private javax.swing.JRadioButton rbtnFClass;
    private javax.swing.JRadioButton rbtnReturn;
    private javax.swing.JRadioButton rbtnSingle;
    private javax.swing.JRadioButton rbtnVat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextArea txtReceipt;
    private javax.swing.JTextField txtSname;
    private javax.swing.JTextField txtStotal;
    private javax.swing.JTextField txtTax;
    private javax.swing.JTextField txtTel;
    public static javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
